CREATE DATABASE IF NOT EXISTS todos;
USE todos;

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    username VARCHAR(20) NOT NULL ,
    email VARCHAR(50) NOT NULL ,
    createdAt TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT  CURRENT_TIMESTAMP
);

CREATE TABLE schedules (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    user_id BIGINT NOT NULL ,
    title VARCHAR(20) NOT NULL ,
    contents TEXT NOT NULL ,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE comments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    schedules_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    comments TEXT NOT NULL ,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (schedules_id) REFERENCES schedules(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);